[project]
name = "agentic-kernel"
version = "0.1.0"
description = "Agentic Kernel - Enhanced Semantic Kernel Framework with Custom Plugins"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "AgenticFleet Team" }
]
dependencies = [
    "semantic-kernel[openai]>=1.2.1",  # Core SK with OpenAI support only
    "chainlit==2.4.400",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",  # Core Pydantic only
    "requests>=2.31.0",  # For web requests
    "beautifulsoup4>=4.12.0",  # For web scraping
    "python-magic>=0.4.27",  # For file type detection
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.12.0",  # For mocking in tests
    "responses>=0.24.1",  # For mocking HTTP requests in tests
]
dev = [
    "black>=24.0.0",
    "isort>=5.13.0",
    "mypy>=1.8.0",
    "ruff>=0.2.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/agenticfleet"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
asyncio_mode = "auto"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.12"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
line-length = 88
target-version = "py312"
