[project]
name = "AgenticFleet"
github = "https://github.com/yourusername/AgenticFleet-Labs"
enable_telemetry = true
user_env = []

[features]
multi_modal = true
code_execution = true
chat_settings = true
chat_profiles = true
streaming_enabled = true

[UI]
name = "AgenticFleet"
description = "Enhanced AutoGen Framework with Custom Agents"
default_expand_messages = false
hide_cot = false
github = "https://github.com/yourusername/AgenticFleet-Labs"
mcp = true
theme = "dark"
show_prompt_playground = true

[meta]
generated_by = "AgenticFleet"
